site_name: NovaSec
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
  - Plugin Development: plugin_development.md
